### ISSUE TITLE
Hi there!

### ISSUE THREAD

**Issue by denisdinkevich** [gharezlak/highlight_search#1]
Hey @gharezlak!  Pretty cool stuff! I am wondering if you can kindly walk me through adding/customizing the sources to search through. Many thanks for your attention and input as well! Cheers, Denis

**Comment by gharezlak** [comment]
Hey @denisdinkevich 

Thanks for the interest. Adding/Customizing other sources is actually pretty easy. You just need to figure out what the API query looks like in the URLs for different sites. 

For example, if you perform a search on LinkedIn for my name, you'll notice that the resulting URL in your browser is: 

https://www.linkedin.com/search/results/index/?keywords=greg%20harezlak&origin=GLOBAL_SEARCH_HEADER

The custom bit of that URL is: "greg%20harezlak"

So, in order to add LinkedIn to the sources, you simply need to replace the white space between search terms the value from the highlighted field with a %:

field_string = "Greg Harezlak"
new_string = field_string.replace(" ", "%");
query_url = "https://www.linkedin.com/search/results/index/?keywords=" + new_string + "&origin=GLOBAL_SEARCH_HEADER" 

//open new tab with query_url as the target

make sense?

**Comment by denisdinkevich** [comment]
Absolutely! Everything aside from your comment re "open new tab with query_url as the target". Could you please kindly let me know what that means? Thanks 😄

**Comment by denisdinkevich** [comment]
Ah, I got it. Thanks mate! 😂
